from __future__ import annotations

SHEET_ORDER = [
    "README",
    "Master_Experiments",
    "Experiment_Definitions",
    "Search_Spaces",
    "Study_Design",
    "Study_Rigor_Checklist",
    "Analysis_Plan",
    "Factors",
    "Fixed_Controls",
    "Constraints",
    "Blocking_and_Replication",
    "Generated_Design_Matrix",
    "Effect_Summaries",
    "Study_Review",
    "Artifact_Registry",
    "Fixed_Configs",
    "Objectives",
    "Machine_Status",
    "Trial_Results",
    "Summary_Outputs",
    "Data_Selection_Design",
    "Grouping_Strategy_Map",
    "Data_Profile",
    "Run_Log",
    "Decision_Log",
    "Confirmatory_Set",
    "Thesis_Map",
    "Dictionary_Validation",
    "Dashboard",
    "Claim_Ledger",
    "AI_Usage_Log",
    "Ethics_Governance_Notes",
]

STAGE_V2 = [
    "Stage 1 - Target lock",
    "Stage 2 - Split lock",
    "Stage 3 - Model lock",
    "Stage 4 - Feature/preprocessing lock",
    "Stage 5 - Confirmatory analysis",
    "Stage 6 - Robustness analysis",
    "Stage 7 - Exploratory extension",
]

MASTER_COLUMNS = [
    "Experiment_ID",
    "Short_Title",
    "Category",
    "Evidential_Role",
    "Stage",
    "Priority",
    "Decision_Supported",
    "Exact_Question",
    "Hypothesis_or_Expectation",
    "Manipulated_Factor",
    "Held_Constant_Controls",
    "Dataset_Scope",
    "Target_Definition",
    "Split_Logic",
    "Leakage_Risk",
    "Leakage_Control",
    "Models_Compared",
    "Primary_Metric",
    "Secondary_Metrics",
    "Robustness_Checks",
    "Decision_Criterion",
    "Success_Pattern",
    "Failure_or_Warning_Pattern",
    "Threats_to_Validity",
    "Reporting_Destination",
    "Interpretation_Boundary",
    "Status",
    "Owner",
    "Outcome_Summary",
    "Decision_Taken",
    "Notes",
    "Experiment_Ready",
]

RUN_LOG_COLUMNS = [
    "Run_ID",
    "Experiment_ID",
    "Run_Date",
    "Dataset_Name",
    "Data_Subset",
    "Data_Slice_ID",
    "Grouping_Strategy_ID",
    "Code_Commit_or_Version",
    "Config_File_or_Path",
    "Random_Seed",
    "Target",
    "Split_ID_or_Fold_Definition",
    "Train_Group_Rule",
    "Test_Group_Rule",
    "Transfer_Direction",
    "Session_Coverage",
    "Task_Coverage",
    "Modality_Coverage",
    "Model",
    "Feature_Set",
    "Run_Type",
    "Affects_Frozen_Pipeline",
    "Eligible_for_Method_Decision",
    "Sample_Count",
    "Class_Counts",
    "Imbalance_Status",
    "Leakage_Check_Status",
    "Primary_Metric_Value",
    "Secondary_Metric_1",
    "Secondary_Metric_2",
    "Robustness_Output_Summary",
    "Result_Summary",
    "Preliminary_Interpretation",
    "Reviewed",
    "Used_in_Thesis",
    "Artifact_Path",
    "Notes",
]

EXPERIMENT_DEFINITIONS_COLUMNS = [
    "experiment_id",
    "enabled",
    "start_section",
    "end_section",
    "base_artifact_id",
    "target",
    "cv",
    "model",
    "subject",
    "train_subject",
    "test_subject",
    "filter_task",
    "filter_modality",
    "reuse_policy",
    "search_space_id",
]

SEARCH_SPACES_COLUMNS = [
    "search_space_id",
    "enabled",
    "optimization_mode",
    "parameter_name",
    "parameter_values",
    "parameter_scope",
    "objective_metric",
    "max_trials",
    "notes",
]

STUDY_DESIGN_COLUMNS = [
    "study_id",
    "study_name",
    "enabled",
    "study_type",
    "intent",
    "question",
    "generalization_claim",
    "start_section",
    "end_section",
    "base_artifact_id",
    "primary_metric",
    "secondary_metrics",
    "cv_scheme",
    "nested_cv",
    "external_validation_planned",
    "blocking_strategy",
    "randomization_strategy",
    "replication_mode",
    "replication_strategy",
    "num_repeats",
    "random_seed_policy",
    "stopping_rule",
    "notes",
]

STUDY_RIGOR_CHECKLIST_COLUMNS = [
    "study_id",
    "leakage_risk_reviewed",
    "deployment_boundary_defined",
    "unit_of_analysis_defined",
    "data_hierarchy_defined",
    "missing_data_plan",
    "class_imbalance_plan",
    "subgroup_plan",
    "fairness_or_applicability_notes",
    "reporting_checklist_completed",
    "risk_of_bias_reviewed",
    "confirmatory_lock_applied",
    "analysis_notes",
]

ANALYSIS_PLAN_COLUMNS = [
    "study_id",
    "primary_contrast",
    "secondary_contrasts",
    "aggregation_level",
    "uncertainty_method",
    "multiplicity_handling",
    "interaction_reporting_policy",
    "interpretation_rules",
    "notes",
]

FACTORS_COLUMNS = [
    "study_id",
    "factor_name",
    "section_name",
    "parameter_path",
    "factor_type",
    "levels",
]

FIXED_CONTROLS_COLUMNS = [
    "study_id",
    "parameter_path",
    "value",
]

CONSTRAINTS_COLUMNS = [
    "study_id",
    "if_factor",
    "if_level",
    "disallow_factor",
    "disallow_level",
    "reason",
]

BLOCKING_AND_REPLICATION_COLUMNS = [
    "study_id",
    "block_type",
    "block_value",
    "repeat_id",
    "seed",
]

GENERATED_DESIGN_MATRIX_COLUMNS = [
    "study_id",
    "trial_id",
    "cell_id",
    "factor_settings_json",
    "start_section",
    "end_section",
    "base_artifact_id",
    "resolved_params_json",
    "status",
]

ARTIFACT_REGISTRY_COLUMNS = [
    "artifact_id",
    "artifact_type",
    "run_id",
    "status",
    "created_at",
    "path",
    "upstream_artifact_ids",
    "config_hash",
    "code_ref",
    "notes",
]

FIXED_CONFIGS_COLUMNS = [
    "config_key",
    "config_value",
    "scope",
    "locked",
    "owner",
    "last_updated",
    "notes",
]

OBJECTIVES_COLUMNS = [
    "objective_id",
    "objective_text",
    "stage",
    "linked_experiment_id",
    "primary_metric",
    "success_criterion",
    "status",
    "notes",
]

MACHINE_STATUS_COLUMNS = [
    "machine_id",
    "hostname",
    "environment_name",
    "python_version",
    "gpu",
    "status",
    "last_checked",
    "notes",
]

TRIAL_RESULTS_COLUMNS = [
    "trial_id",
    "experiment_id",
    "run_id",
    "status",
    "primary_metric_name",
    "primary_metric_value",
    "report_path",
    "metrics_path",
    "artifact_bundle",
    "notes",
    "study_id",
    "cell_id",
    "factor_settings_json",
    "resolved_params_json",
]

SUMMARY_OUTPUTS_COLUMNS = [
    "summary_type",
    "summary_key",
    "primary_metric_name",
    "primary_metric_value",
    "run_id",
    "experiment_id",
    "start_section",
    "end_section",
    "model",
    "cv",
    "target",
    "xai_method",
    "report_path",
    "notes",
]

EFFECT_SUMMARIES_COLUMNS = [
    "study_id",
    "summary_type",
    "summary_key",
    "factor_level_key",
    "interaction_key",
    "primary_metric_name",
    "mean_primary_metric_value",
    "best_primary_metric_value",
    "best_trial_id",
    "notes",
]

STUDY_REVIEW_COLUMNS = [
    "study_id",
    "study_name",
    "intent",
    "execution_disposition",
    "execution_eligibility_status",
    "warning_count",
    "error_count",
    "missing_fields_json",
    "warnings_json",
    "errors_json",
    "question",
    "generalization_claim",
    "start_section",
    "end_section",
    "factors_json",
    "fixed_controls_json",
    "constraints_json",
    "excluded_combination_count",
    "expected_design_cells",
    "expected_trials",
    "primary_metric",
    "secondary_metrics",
    "cv_scheme",
    "nested_cv",
    "external_validation_planned",
    "blocking_strategy",
    "randomization_strategy",
    "replication_strategy",
    "replication_mode",
    "num_repeats",
    "random_seed_policy",
    "rigor_checklist_status",
    "analysis_plan_status",
    "completed_trials",
    "failed_trials",
    "blocked_trials",
    "dry_run_trials",
    "notes",
]

DATA_SELECTION_COLUMNS = [
    "Data_Slice_ID",
    "Slice_Name",
    "Purpose",
    "Subject_Scope",
    "Session_Scope",
    "Time_Window",
    "Task_Scope",
    "Modality_Scope",
    "Target_Type",
    "Label_Set",
    "Inclusion_Rule",
    "Exclusion_Rule",
    "Class_Balance_Policy",
    "Minimum_Samples_Rule",
    "Leakage_Risk",
    "Valid_Use_Case",
    "Thesis_Use",
    "Notes",
]

GROUPING_STRATEGY_COLUMNS = [
    "Grouping_Strategy_ID",
    "Strategy_Name",
    "Split_Family",
    "Train_Group_Unit",
    "Test_Group_Unit",
    "Grouping_Level",
    "Train_Rule",
    "Test_Rule",
    "Leakage_Safeguard",
    "Suitable_For",
    "Not_Suitable_For",
    "Interpretation_Boundary",
    "Typical_Experiments",
    "Thesis_Section",
    "Notes",
]

DECISION_COLUMNS = [
    "Decision_ID",
    "Decision_Topic",
    "Stage",
    "Candidate_Options",
    "Evidence_Experiments",
    "Decision_Criteria",
    "Chosen_Option",
    "Why_Chosen",
    "Why_Not_Others",
    "Risks_or_Tradeoffs",
    "Grounding_Section_or_Source_Packet",
    "Date_Locked",
    "Freeze_Status",
    "Thesis_Use",
]

CONFIRMATORY_COLUMNS = [
    "Experiment_ID",
    "Short_Title",
    "Final_Pipeline_Version",
    "Claim_Supported",
    "Status",
    "Eligible_to_Run",
    "Completed",
    "Required_for_Main_Claim",
    "Ready_for_Chapter_4",
    "Confirmatory_Eligible",
    "Main_Result_Summary",
    "Robustness_Status",
]

THESIS_MAP_COLUMNS = [
    "Experiment_ID",
    "Chapter",
    "Section",
    "Purpose_in_Thesis",
    "Main_or_Supporting",
    "Method_Choice_or_Method_Application_or_Discussion",
    "What_Claim_or_Decision_It_Supports",
    "Notes_for_Writing",
]

CLAIM_LEDGER_COLUMNS = [
    "Claim_ID",
    "Claim_Text",
    "Claim_Type",
    "Supported_By_Experiments",
    "Evidence_Status",
    "Writing_Location",
    "Interpretation_Limit",
    "Notes",
]

AI_USAGE_COLUMNS = [
    "Entry_ID",
    "Date",
    "Task",
    "Tool",
    "Input_Summary",
    "Output_Summary",
    "What_Was_Adopted",
    "Human_Verification_Status",
    "Thesis_Use",
    "Notes",
]

ETHICS_COLUMNS = [
    "Note_ID",
    "Experiment_ID_or_Decision_ID",
    "Topic",
    "Risk_or_Concern",
    "Mitigation_or_Response",
    "Thesis_Section",
    "Status",
    "Notes",
]

VOCABS = {
    "Category": [
        "Target-definition",
        "Split-design",
        "Model-comparison",
        "Preprocessing-feature",
        "Robustness",
        "Confirmatory core",
        "External exploratory",
    ],
    "Evidential_Role": [
        "Primary confirmatory",
        "Primary-supporting robustness",
        "Secondary decision-support",
        "Secondary decision-support / robustness",
        "Exploratory extension",
    ],
    "Stage": STAGE_V2,
    "Priority": ["Critical", "High", "Medium", "Low"],
    "Status": ["Planned", "Not started", "Running", "Completed", "On hold", "Dropped"],
    "Reporting_Destination": [
        "Chapter 3 Method choice",
        "Chapter 4 Main results",
        "Chapter 4 Supporting robustness",
        "Chapter 5 Discussion",
        "Appendix",
    ],
    "Reviewed": ["No", "Yes"],
    "Used_in_Thesis": ["No", "Yes"],
    "Freeze_Status": ["Open", "Locked"],
    "Run_Type": ["Pilot", "Decision-support", "Confirmatory", "Robustness", "Exploratory"],
    "Affects_Frozen_Pipeline": ["No", "Yes"],
    "Eligible_for_Method_Decision": ["No", "Yes"],
    "Claim_Type": [
        "Method-choice",
        "Confirmatory finding",
        "Robustness support",
        "Exploratory observation",
    ],
    "Evidence_Status": ["open", "partial", "supported"],
    "Writing_Location": ["Chapter 3", "Chapter 4", "Chapter 5", "Appendix"],
    "Human_Verification_Status": ["Not reviewed", "Partially verified", "Verified"],
    "Ethics_Status": ["Open", "Monitoring", "Closed"],
    "Ethics_Topic": [
        "Data governance",
        "Bias/fairness",
        "Interpretation limits",
        "AI/tool transparency",
        "Reproducibility",
        "Other",
    ],
    "Required_for_Main_Claim": ["No", "Yes"],
    "Ready_for_Chapter_4": ["No", "Yes"],
    "YesNo": ["No", "Yes"],
    "Subject_Scope": ["all_subjects", "single_subject", "cross_person_transfer"],
    "Session_Scope": [
        "all_sessions",
        "early_only",
        "late_only",
        "held_out_session",
        "custom_window",
    ],
    "Task_Scope": [
        "pooled_all_tasks",
        "passive_only",
        "emo_only",
        "rating_only",
        "task_specific_other",
    ],
    "Modality_Scope": ["pooled_all_modalities", "audio_only", "video_only", "audiovisual_only"],
    "Class_Balance_Policy": ["as_is", "balanced_subset", "weighted_only", "min_count_threshold"],
    "Split_Family": ["within_subject", "cross_person", "temporal", "weak_split_demo", "diagnostic"],
    "Imbalance_Status": ["unknown", "balanced", "mild_imbalance", "severe_imbalance"],
    "Leakage_Check_Status": ["not_checked", "passed", "warning", "failed"],
    "Thesis_Use_Tag": [
        "method_choice",
        "main_confirmatory",
        "supporting_robustness",
        "discussion_limitations",
        "appendix_exploratory",
    ],
    "Use_Case": [
        "method_choice",
        "confirmatory_within_person",
        "confirmatory_cross_person_transfer",
        "robustness_support",
        "weak_split_demo_only",
        "diagnostic_only",
        "exploratory_only",
    ],
    "Group_Unit": [
        "subject",
        "session",
        "task",
        "modality",
        "subject_session",
        "task_modality",
        "custom_group",
    ],
    "Grouping_Level": [
        "within_subject",
        "across_subject",
        "session_level",
        "task_level",
        "modality_level",
        "task_modality_level",
        "mixed_level",
    ],
    "Transfer_Direction": ["none_or_within_subject", "A_to_B", "B_to_A", "bidirectional", "custom"],
    "Leakage_Risk_Level": ["low", "medium", "high", "critical"],
    "Target_Type": ["coarse_affect", "binary_valence_like", "fine_emotion", "custom_target"],
    "Execution_Section": [
        "dataset_selection",
        "feature_cache_build",
        "feature_matrix_load",
        "spatial_validation",
        "model_fit",
        "interpretability",
        "evaluation",
    ],
    "Reuse_Policy": ["auto", "require_explicit_base", "disallow"],
    "Search_Optimization_Mode": ["deterministic_grid", "optuna"],
    "Search_Parameter_Scope": ["parameter", "segment", "xai"],
    "Study_Type": ["single_experiment", "full_factorial", "fractional_factorial", "custom_matrix"],
    "Study_Intent": ["exploratory", "confirmatory"],
    "Factor_Type": ["categorical", "boolean", "ordinal", "numeric"],
    "Replication_Mode": ["none", "fixed_repeats", "custom_blocks"],
    "Replication_Strategy": ["none", "fixed_repeats", "blocked_repeats", "custom"],
    "Blocking_Strategy": ["none", "by_subject", "by_task", "by_modality", "custom"],
    "Randomization_Strategy": [
        "none",
        "fixed_order",
        "random_per_trial",
        "random_per_repeat",
        "custom",
    ],
    "Random_Seed_Policy": ["fixed", "per_repeat", "per_cell"],
    "Block_Type": ["none", "subject", "task", "modality", "custom"],
    "Design_Cell_Status": ["planned", "dry_run", "completed", "failed", "blocked"],
    "Aggregation_Level": ["trial", "cell", "subject", "fold", "group"],
    "Uncertainty_Method": [
        "none",
        "standard_error",
        "confidence_interval",
        "bootstrap",
        "permutation",
    ],
    "Multiplicity_Handling": [
        "none",
        "bonferroni",
        "holm",
        "fdr",
        "hierarchical_gatekeeping",
        "pre_specified_contrasts_only",
    ],
    "Interaction_Reporting_Policy": [
        "none",
        "descriptive_only",
        "pre_specified_only",
        "all_two_way_descriptive",
    ],
    "Study_Review_Disposition": ["allowed", "warning", "blocked"],
    "Study_Eligibility_Status": ["eligible", "eligible_with_warnings", "blocked"],
}

DEFINITIONS = [
    (
        "confirmatory",
        "Pre-specified, locked-pipeline evidence analysis supporting main thesis claims.",
    ),
    ("decision-support", "Method-choice analysis performed before locking confirmatory settings."),
    ("exploratory", "Hypothesis-generating extension outside confirmatory core."),
    (
        "data slice",
        "Explicit subset policy over subjects/sessions/tasks/modalities/labels used by runs.",
    ),
    (
        "grouping strategy",
        "Explicit train/test grouping logic and split family for claim-matched evaluation.",
    ),
    (
        "weak split demo",
        "Intentionally weak split used only to demonstrate inflation risk; not confirmatory evidence.",
    ),
    ("construct validity", "How well labels/features operationalize intended constructs."),
    ("internal validity", "Protection against confounds and leakage in design and execution."),
    ("statistical conclusion validity", "Reliability of metric-based inference."),
    ("external validity", "Extent findings transfer to other data contexts."),
    ("leakage", "Train-test information contamination that inflates apparent performance."),
    ("domain shift", "Distribution shift between train and test domains."),
    (
        "interpretability stability",
        "Consistency of model-behavior explanation signals across folds.",
    ),
]


def build_experiments() -> list[dict[str, str]]:
    base = {
        "Priority": "Medium",
        "Decision_Supported": "Methodological decision support.",
        "Hypothesis_or_Expectation": "Evaluate under leakage-aware claim-matched split logic before interpretation.",
        "Held_Constant_Controls": "Dataset index version, train-only fitting policy, metric definitions, seed policy, artifact schema.",
        "Dataset_Scope": "Internal repeated-session BAS2 dataset (sub-001 and sub-002) unless explicitly external.",
        "Target_Definition": "coarse_affect unless this experiment manipulates target granularity.",
        "Split_Logic": "Claim-matched leakage-safe split strategy.",
        "Leakage_Risk": "Performance inflation if split logic or fit scope leaks train/test information.",
        "Leakage_Control": "Predefined split manifests, train-only fitting, frozen transfer where applicable, no test-driven tuning.",
        "Models_Compared": "ridge baseline unless model family is manipulated.",
        "Primary_Metric": "Balanced accuracy",
        "Secondary_Metrics": "Macro-F1; class-wise recall; accuracy",
        "Robustness_Checks": "Fold-level checks and stress controls where relevant.",
        "Decision_Criterion": "Pre-specified criterion recorded before interpretation.",
        "Success_Pattern": "Stable claim-consistent performance without leakage indicators.",
        "Failure_or_Warning_Pattern": "Weak-split inflation, instability, class collapse, or directionally inconsistent evidence.",
        "Threats_to_Validity": "Class imbalance, sample limits, domain shift, and model/split sensitivity.",
        "Reporting_Destination": "Chapter 3 Method choice",
        "Interpretation_Boundary": "Interpret only under stated split logic/evidence tier; no causal or localization claims.",
        "Status": "Planned",
        "Owner": "Khaled (thesis author)",
        "Outcome_Summary": "",
        "Decision_Taken": "",
        "Notes": "",
    }
    rows = [
        {
            "Experiment_ID": "E01",
            "Short_Title": "Target granularity experiment",
            "Category": "Target-definition",
            "Evidential_Role": "Secondary decision-support",
            "Stage": "Stage 1 - Target lock",
            "Priority": "High",
            "Decision_Supported": "Final target lock",
            "Exact_Question": "Should the thesis use fine-grained emotion labels, three-class coarse affect, or binary valence-like labels?",
            "Hypothesis_or_Expectation": "coarse_affect likely balances construct validity, class balance, and learnability.",
            "Manipulated_Factor": "Target definition",
            "Target_Definition": "fine emotion vs coarse_affect vs binary valence-like",
            "Split_Logic": "within_subject_loso_session for primary comparison; frozen transfer as secondary check",
            "Decision_Criterion": "Prefer target balancing construct validity, class balance, sample sufficiency, and learnability under claim-matched evaluation.",
        },
        {
            "Experiment_ID": "E02",
            "Short_Title": "Task pooling experiment",
            "Category": "Target-definition",
            "Evidential_Role": "Secondary decision-support",
            "Stage": "Stage 1 - Target lock",
            "Decision_Supported": "Task pooling policy",
            "Exact_Question": "Should the main target be learned across all tasks together, or separately by task?",
            "Manipulated_Factor": "Pooling strategy by task",
        },
        {
            "Experiment_ID": "E03",
            "Short_Title": "Modality pooling experiment",
            "Category": "Target-definition",
            "Evidential_Role": "Secondary decision-support",
            "Stage": "Stage 1 - Target lock",
            "Decision_Supported": "Modality pooling policy",
            "Exact_Question": "Should audio, video, and audiovisual conditions be pooled or modeled separately?",
            "Manipulated_Factor": "Pooling strategy by modality",
        },
        {
            "Experiment_ID": "E04",
            "Short_Title": "Split-strength stress test",
            "Category": "Split-design",
            "Evidential_Role": "Secondary decision-support",
            "Stage": "Stage 2 - Split lock",
            "Priority": "High",
            "Decision_Supported": "Primary split policy",
            "Exact_Question": "How much do conclusions change under weaker split strategies compared with session-held-out evaluation?",
            "Manipulated_Factor": "Split logic",
            "Split_Logic": "record-wise random split vs weaker grouped split vs within-person leave-one-session-out",
            "Leakage_Risk": "High under weak splits",
            "Decision_Criterion": "Retain strictest split matching claim; weaker splits only as inflation/leakage demonstrations.",
        },
        {
            "Experiment_ID": "E05",
            "Short_Title": "Cross-person transfer design",
            "Category": "Split-design",
            "Evidential_Role": "Secondary decision-support",
            "Stage": "Stage 2 - Split lock",
            "Priority": "High",
            "Decision_Supported": "Cross-person transfer framing",
            "Exact_Question": "How should cross-person generalization be framed and evaluated?",
            "Manipulated_Factor": "Transfer protocol",
            "Split_Logic": "frozen train-on-A/test-on-B and reverse direction",
            "Leakage_Control": "Fit only on train subject; no test subject re-fit/re-tune",
            "Decision_Criterion": "Keep frozen directional transfer as clean cross-case test.",
            "Interpretation_Boundary": "Transfer evidence under domain shift, not population-level generalization.",
        },
        {
            "Experiment_ID": "E06",
            "Short_Title": "Linear model family comparison",
            "Category": "Model-comparison",
            "Evidential_Role": "Secondary decision-support",
            "Stage": "Stage 3 - Model lock",
            "Priority": "High",
            "Decision_Supported": "Model family lock",
            "Exact_Question": "Which linear model is the most appropriate default: ridge, logistic regression, or linear SVM?",
            "Manipulated_Factor": "Model family",
            "Models_Compared": "ridge vs logreg vs linearsvc",
            "Decision_Criterion": "Prefer simplest model with comparable predictive performance and better robustness/stability.",
        },
        {
            "Experiment_ID": "E07",
            "Short_Title": "Class weighting experiment",
            "Category": "Model-comparison",
            "Evidential_Role": "Secondary decision-support",
            "Stage": "Stage 3 - Model lock",
            "Decision_Supported": "Weighting policy",
            "Exact_Question": "Does class weighting improve fairness across classes without creating instability?",
            "Manipulated_Factor": "Weighting strategy",
        },
        {
            "Experiment_ID": "E08",
            "Short_Title": "Hyperparameter strategy experiment",
            "Category": "Model-comparison",
            "Evidential_Role": "Secondary decision-support",
            "Stage": "Stage 3 - Model lock",
            "Decision_Supported": "Tuning policy",
            "Exact_Question": "Are fixed conservative hyperparameters sufficient, or does light nested tuning materially improve results?",
            "Manipulated_Factor": "Tuning strategy",
            "Decision_Criterion": "Keep fixed settings unless nested tuning yields a clear and stable gain.",
        },
        {
            "Experiment_ID": "E09",
            "Short_Title": "Whole-brain versus ROI experiment",
            "Category": "Preprocessing-feature",
            "Evidential_Role": "Secondary decision-support",
            "Stage": "Stage 4 - Feature/preprocessing lock",
            "Decision_Supported": "Feature representation lock",
            "Exact_Question": "Should the primary representation remain whole-brain masked voxels or use theory-justified ROIs?",
            "Manipulated_Factor": "Feature space",
        },
        {
            "Experiment_ID": "E10",
            "Short_Title": "Dimensionality reduction experiment",
            "Category": "Preprocessing-feature",
            "Evidential_Role": "Secondary decision-support",
            "Stage": "Stage 4 - Feature/preprocessing lock",
            "Decision_Supported": "Feature reduction policy",
            "Exact_Question": "Does unsupervised dimensionality reduction improve performance or stability enough to justify added complexity?",
            "Manipulated_Factor": "Feature reduction strategy",
        },
        {
            "Experiment_ID": "E11",
            "Short_Title": "Scaling and normalization experiment",
            "Category": "Preprocessing-feature",
            "Evidential_Role": "Secondary decision-support",
            "Stage": "Stage 4 - Feature/preprocessing lock",
            "Decision_Supported": "Scaling policy lock",
            "Exact_Question": "How sensitive are the results to scaling strategy?",
            "Manipulated_Factor": "Scaling policy",
        },
        {
            "Experiment_ID": "E12",
            "Short_Title": "Permutation test experiment",
            "Category": "Robustness",
            "Evidential_Role": "Primary-supporting robustness",
            "Stage": "Stage 6 - Robustness analysis",
            "Priority": "High",
            "Decision_Supported": "Chance-level distinguishability support",
            "Exact_Question": "Are the main predictive results distinguishable from chance under the exact same split logic?",
            "Manipulated_Factor": "Label structure (true vs permuted)",
            "Split_Logic": "exact confirmatory split logic with train-only permutation",
            "Secondary_Metrics": "Empirical p-value; null distribution summary",
            "Reporting_Destination": "Chapter 4 Supporting robustness",
        },
        {
            "Experiment_ID": "E13",
            "Short_Title": "Trivial baseline experiment",
            "Category": "Robustness",
            "Evidential_Role": "Primary-supporting robustness",
            "Stage": "Stage 6 - Robustness analysis",
            "Priority": "High",
            "Decision_Supported": "Non-trivial predictive value support",
            "Exact_Question": "Does the final model clearly outperform trivial baselines?",
            "Manipulated_Factor": "Baseline type",
            "Models_Compared": "Final locked model vs trivial baselines",
            "Reporting_Destination": "Chapter 4 Supporting robustness",
        },
        {
            "Experiment_ID": "E14",
            "Short_Title": "Stability of explanation experiment",
            "Category": "Robustness",
            "Evidential_Role": "Primary-supporting robustness",
            "Stage": "Stage 6 - Robustness analysis",
            "Priority": "High",
            "Decision_Supported": "Interpretability stability support",
            "Exact_Question": "Are linear coefficients or importance patterns stable across held-out-session folds?",
            "Manipulated_Factor": "Fold identity",
            "Primary_Metric": "Mean pairwise coefficient correlation",
            "Secondary_Metrics": "Sign consistency; top-k overlap",
            "Reporting_Destination": "Chapter 4 Supporting robustness",
            "Interpretation_Boundary": "Model-behavior evidence only; not direct neural localization.",
        },
        {
            "Experiment_ID": "E15",
            "Short_Title": "Sensitivity to subset exclusion",
            "Category": "Robustness",
            "Evidential_Role": "Secondary decision-support / robustness",
            "Stage": "Stage 6 - Robustness analysis",
            "Decision_Supported": "Sensitivity framing",
            "Exact_Question": "Do the main conclusions depend excessively on one subset, such as one task or modality?",
            "Manipulated_Factor": "Subset inclusion",
            "Reporting_Destination": "Chapter 5 Discussion",
        },
        {
            "Experiment_ID": "E16",
            "Short_Title": "Final within-person confirmatory analysis",
            "Category": "Confirmatory core",
            "Evidential_Role": "Primary confirmatory",
            "Stage": "Stage 5 - Confirmatory analysis",
            "Priority": "Critical",
            "Decision_Supported": "Primary confirmatory claim",
            "Exact_Question": "Does the final locked pipeline show meaningful within-person held-out-session generalization?",
            "Manipulated_Factor": "None; final frozen pipeline",
            "Target_Definition": "Locked target after Stage 1 target lock",
            "Split_Logic": "within_subject_loso_session",
            "Models_Compared": "Final locked model",
            "Decision_Criterion": "Primary evidential core of thesis.",
            "Reporting_Destination": "Chapter 4 Main results",
        },
        {
            "Experiment_ID": "E17",
            "Short_Title": "Final cross-person transfer analysis",
            "Category": "Confirmatory core",
            "Evidential_Role": "Primary confirmatory",
            "Stage": "Stage 5 - Confirmatory analysis",
            "Priority": "Critical",
            "Decision_Supported": "Secondary confirmatory transfer claim",
            "Exact_Question": "Does the final locked pipeline transfer meaningfully across individuals under frozen directional transfer?",
            "Manipulated_Factor": "None; final frozen pipeline",
            "Target_Definition": "Locked target after Stage 1 target lock",
            "Split_Logic": "frozen_cross_person_transfer both directions",
            "Models_Compared": "Final locked model",
            "Decision_Criterion": "Interpret as cross-case transfer evidence under domain shift.",
            "Reporting_Destination": "Chapter 4 Main results",
            "Interpretation_Boundary": "Directional transfer evidence only; not population-level generalization.",
        },
        {
            "Experiment_ID": "E18",
            "Short_Title": "External open-source split replication",
            "Category": "External exploratory",
            "Evidential_Role": "Exploratory extension",
            "Stage": "Stage 7 - Exploratory extension",
            "Priority": "Low",
            "Decision_Supported": "External split-consistency exploration",
            "Exact_Question": "Does the same leakage-aware split logic materially affect conclusions on a compatible external open-source dataset?",
            "Manipulated_Factor": "Dataset source",
            "Dataset_Scope": "External open-source dataset if available and approved",
            "Reporting_Destination": "Appendix",
        },
        {
            "Experiment_ID": "E19",
            "Short_Title": "External open-source model portability",
            "Category": "External exploratory",
            "Evidential_Role": "Exploratory extension",
            "Stage": "Stage 7 - Exploratory extension",
            "Priority": "Low",
            "Decision_Supported": "External model portability exploration",
            "Exact_Question": "Does the relative ranking of reasonable model choices remain similar on external data?",
            "Manipulated_Factor": "Dataset source with same small model set",
            "Dataset_Scope": "External open-source dataset if available and approved",
            "Models_Compared": "ridge vs logreg vs linearsvc",
            "Reporting_Destination": "Appendix",
        },
    ]
    out: list[dict[str, str]] = []
    for row in rows:
        item = dict(base)
        item.update(row)
        out.append(item)
    return out

