"""Central configuration helpers for paths and defaults."""

from .paths import (
    DEFAULT_BASELINE_MODELS_DIR,
    DEFAULT_BASELINE_REPORTS_DIR,
    DEFAULT_DECISION_SUPPORT_OUTPUT_ROOT,
    DEFAULT_DECISION_SUPPORT_REGISTRY,
    DEFAULT_EXPERIMENT_REPORTS_ROOT,
    DEFAULT_SPM_GLM_EXTRACTION_OUT,
    DEFAULT_WORKBOOK_OUTPUT_DIR,
    DEFAULT_WORKBOOK_TEMPLATE,
    OUTPUTS_ROOT,
    PROJECT_ROOT,
    ensure_default_output_dirs,
)

__all__ = [
    "PROJECT_ROOT",
    "OUTPUTS_ROOT",
    "DEFAULT_DECISION_SUPPORT_REGISTRY",
    "DEFAULT_WORKBOOK_TEMPLATE",
    "DEFAULT_DECISION_SUPPORT_OUTPUT_ROOT",
    "DEFAULT_EXPERIMENT_REPORTS_ROOT",
    "DEFAULT_BASELINE_REPORTS_DIR",
    "DEFAULT_BASELINE_MODELS_DIR",
    "DEFAULT_SPM_GLM_EXTRACTION_OUT",
    "DEFAULT_WORKBOOK_OUTPUT_DIR",
    "ensure_default_output_dirs",
]
