from __future__ import annotations

# Public contract versions.
WORKBOOK_SCHEMA_VERSION = "workbook-v1"
COMPILED_MANIFEST_SCHEMA_VERSION = "compiled-manifest-v1"
ARTIFACT_SCHEMA_VERSION = "artifact-v1"
WORKBOOK_WRITEBACK_SCHEMA_VERSION = "workbook-writeback-v1"
SUMMARY_RESULT_SCHEMA_VERSION = "summary-result-v1"

SUPPORTED_WORKBOOK_SCHEMA_VERSIONS = frozenset({WORKBOOK_SCHEMA_VERSION})
SUPPORTED_COMPILED_MANIFEST_SCHEMA_VERSIONS = frozenset(
    {COMPILED_MANIFEST_SCHEMA_VERSION}
)
SUPPORTED_ARTIFACT_SCHEMA_VERSIONS = frozenset({ARTIFACT_SCHEMA_VERSION})
SUPPORTED_WORKBOOK_WRITEBACK_SCHEMA_VERSIONS = frozenset(
    {WORKBOOK_WRITEBACK_SCHEMA_VERSION}
)
SUPPORTED_SUMMARY_RESULT_SCHEMA_VERSIONS = frozenset({SUMMARY_RESULT_SCHEMA_VERSION})

# Deterministic workbook metadata placement (README sheet).
WORKBOOK_SCHEMA_METADATA_START_ROW = 45
WORKBOOK_SCHEMA_METADATA_KEY_COLUMN = 1
WORKBOOK_SCHEMA_METADATA_VALUE_COLUMN = 2
WORKBOOK_SCHEMA_METADATA_HEADER_KEY = "Schema_Metadata_Key"
WORKBOOK_SCHEMA_METADATA_HEADER_VALUE = "Value"
WORKBOOK_SCHEMA_METADATA_ROWS: tuple[tuple[str, str], ...] = (
    ("workbook_schema_version", WORKBOOK_SCHEMA_VERSION),
    ("compiled_manifest_schema_version", COMPILED_MANIFEST_SCHEMA_VERSION),
    ("artifact_schema_version", ARTIFACT_SCHEMA_VERSION),
    ("workbook_writeback_schema_version", WORKBOOK_WRITEBACK_SCHEMA_VERSION),
    ("summary_result_schema_version", SUMMARY_RESULT_SCHEMA_VERSION),
)

